#ifndef INCLUDE_GUARD
#define INCLUDE_GUARD

#define PROJECT_NAME "mpp"
#define PROJECT_VER "1.2.0"
#define PROJECT_VER_MAJOR "1"
#define PROJECT_VER_MINOR "2"
#define PROJECT_VER_PATCH "0"

#endif // INCLUDE_GUARD
