#ifndef INCLUDE_GUARD
#define INCLUDE_GUARD

#define PROJECT_NAME "mpp"
#define PROJECT_VER "2.3.5"
#define PROJECT_VER_MAJOR "2"
#define PROJECT_VER_MINOR "3"
#define PROJECT_VER_PATCH "5"

#endif // INCLUDE_GUARD
