name: C/C++ CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: configure
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug -D MPP_BUILD_SHARED_LIBS=OFF -D MPP_ENABLE_COVERAGE=ON

    - name: build
      run: cmake --build build --config Debug -j4

    - name: test
      run: |
        cd build
        ctest --build-config Debug
    - name: collect code coverage
      run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
